import SwiftUI
import SharedModels
import Summarization


struct OverviewSummaryCard: View {
    let summary: Summary
    let periodTitle: String
    let sessionCount: Int
    let sessionsInPeriod: [RecordingSession]
    let coordinator: AppCoordinator
    let onRegenerate: (() async -> Void)?
    let wrapAction: (() -> Void)?
    let wrapIsLoading: Bool
    
    @State private var isRegenerating = false
    
    var body: some View {
        VStack(alignment: .leading, spacing: 16) {
            // Header with action buttons
            headerSection
            
            // Summary text - larger, selectable, in its own container
            summaryTextSection
            
            // Topics tags
            if let topicsJSON = summary.topicsJSON {
                TopicTagsView(topicsJSON: topicsJSON)
            }
            
            // Engine tier badge
            if let engineTier = summary.engineTier {
                engineBadge(tier: engineTier)
            }
        }
        .padding(.vertical, 8)
    }
    
    // MARK: - Header Section
    
    private var headerSection: some View {
        HStack(alignment: .top, spacing: 12) {
            VStack(alignment: .leading, spacing: 4) {
                Text("📝 \(periodTitle)")
                    .font(.headline)
                Text("Based on \(sessionCount) session\(sessionCount == 1 ? "" : "s")")
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }
            
            Spacer()
            
            // Copy button
            Button {
                UIPasteboard.general.string = summary.text
                coordinator.showSuccess("Summary copied")
            } label: {
                Image(systemName: "doc.on.doc")
                    .font(.title3)
                    .foregroundStyle(.blue)
                    .frame(width: 44, height: 44)
                    .background(Color.blue.opacity(0.1))
                    .cornerRadius(8)
            }
            .buttonStyle(.plain)
            
            // Regenerate button (optional)
            if let onRegenerate {
                Button {
                    Task {
                        isRegenerating = true
                        await onRegenerate()
                        isRegenerating = false
                    }
                } label: {
                    if isRegenerating {
                        ProgressView()
                            .frame(width: 44, height: 44)
                    } else {
                        Image(systemName: "arrow.clockwise")
                            .font(.title3)
                            .foregroundStyle(.orange)
                            .frame(width: 44, height: 44)
                            .background(Color.orange.opacity(0.1))
                            .cornerRadius(8)
                    }
                }
                .buttonStyle(.plain)
                .disabled(isRegenerating)
            }

            if let wrapAction {
                Button {
                    wrapAction()
                } label: {
                    if wrapIsLoading {
                        ProgressView()
                            .frame(width: 44, height: 44)
                    } else {
                        Image(systemName: "sparkles")
                            .font(.title3)
                            .foregroundStyle(.purple)
                            .frame(width: 44, height: 44)
                            .background(Color.purple.opacity(0.1))
                            .cornerRadius(8)
                    }
                }
                .buttonStyle(.plain)
                .disabled(isRegenerating || wrapIsLoading)
                .accessibilityLabel("Generate Year Wrap")
            }
        }
    }
    
    // MARK: - Summary Text Section
    
    private var summaryTextSection: some View {
        VStack(alignment: .leading, spacing: 8) {
            // The summary text in a scrollable, selectable container
            ScrollView {
                Text(summary.text)
                    .font(.body)
                    .foregroundStyle(.primary)
                    .textSelection(.enabled)
                    .frame(maxWidth: .infinity, alignment: .leading)
            }
            .frame(minHeight: 120, maxHeight: 200)
            .padding(16)
            .background(Color(.tertiarySystemBackground))
            .cornerRadius(12)
        }
    }
    
    // MARK: - Engine Badge
    
    private func engineBadge(tier: String) -> some View {
        HStack(spacing: 6) {
            Image(systemName: engineIcon(for: tier))
                .font(.caption)
            Text("Generated by \(engineDisplayName(for: tier))")
                .font(.caption)
        }
        .foregroundStyle(.secondary)
    }
    
    // MARK: - Helpers
    
    private func engineIcon(for tier: String) -> String {
        switch tier.lowercased() {
        case "apple": return "apple.intelligence"
        case "basic": return "bolt.fill"
        case "external": return "sparkles"
        case "rollup": return "arrow.triangle.merge"
        case "year wrap": return "sparkles"
        default: return "cpu"
        }
    }
    
    private func engineDisplayName(for tier: String) -> String {
        switch tier.lowercased() {
        case "apple": return "Apple Intelligence"
        case "basic": return "Basic"
        case "external": return "Year Wrapped Pro AI"
        case "rollup": return "Rollup"
        case "year wrap": return "Year Wrap"
        default: return tier.capitalized
        }
    }
}

// MARK: - Insight Session Row

