# =============================================================================
# Life Wrapped — SwiftLint Configuration
# =============================================================================
# Docs: https://realm.github.io/SwiftLint/rule-directory.html
# =============================================================================

# -----------------------------------------------------------------------------
# Included/Excluded Paths
# -----------------------------------------------------------------------------
included:
  - App
  - Extensions
  - WatchApp
  - MacApp
  - Packages

excluded:
  - .build
  - DerivedData
  - Packages/*/.build
  - "**/.build"
  - Tests/Fixtures

# -----------------------------------------------------------------------------
# Enabled Rules (on top of defaults)
# -----------------------------------------------------------------------------
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# -----------------------------------------------------------------------------
# Disabled Rules
# -----------------------------------------------------------------------------
disabled_rules:
  - todo  # We use TODOs actively during development
  - opening_brace  # Conflicts with swift-format sometimes
  - trailing_comma  # Personal preference

# -----------------------------------------------------------------------------
# Rule Configuration
# -----------------------------------------------------------------------------
line_length:
  warning: 120
  error: 150
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 15
  error: 25

function_parameter_count:
  warning: 6
  error: 8

nesting:
  type_level: 3
  function_level: 3

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - db
    - to
    - i
    - j
    - x
    - y
    - ok

type_name:
  min_length: 3
  max_length: 50

large_tuple:
  warning: 4
  error: 5

vertical_whitespace:
  max_empty_lines: 2

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true

# Enforce modifier order
modifier_order:
  preferred_modifier_order:
    - acl
    - setterACL
    - override
    - dynamic
    - mutating
    - lazy
    - final
    - required
    - convenience
    - typeMethods
    - owned

# Custom rules
custom_rules:
  no_print_in_production:
    name: "No print() in production code"
    regex: '\bprint\s*\('
    match_kinds:
      - identifier
    message: "Use os_log or Logger instead of print()"
    severity: warning
    excluded: ".*Tests.*"

  privacy_allowed_comment:
    name: "Privacy-allowed annotation"
    regex: '// PRIVACY-ALLOWED:'
    match_kinds:
      - comment
    message: "Verify this privacy exception is documented"
    severity: warning

# -----------------------------------------------------------------------------
# Reporter
# -----------------------------------------------------------------------------
reporter: "emoji"
