name: LifeWrapped
options:
  bundleIdPrefix: com.jsayram
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "26.1"

settings:
  base:
    SWIFT_VERSION: "6.0"
    SWIFT_STRICT_CONCURRENCY: complete

packages:
  SharedModels:
    path: Packages/SharedModels
  Storage:
    path: Packages/Storage
  InsightsRollup:
    path: Packages/InsightsRollup

targets:
  LifeWrapped:
    type: application
    platform: iOS
    sources:
      - path: App
        excludes:
          - "Resources/Assets.xcassets"
    resources:
      - App/Resources/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: $(BUNDLE_ID_PREFIX).lifewrapped
        INFOPLIST_FILE: App/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: App/Resources/Entitlements.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MACCATALYST: true
        IPHONEOS_DEPLOYMENT_TARGET: "18.0"
        DERIVE_MACCATALYST_PRODUCT_BUNDLE_IDENTIFIER: true
      configs:
        Debug:
          xcconfig: Config/Debug.xcconfig
        Release:
          xcconfig: Config/Release.xcconfig
    dependencies:
      - package: SharedModels
      - target: LifeWrappedWidget
        embed: true

  LifeWrappedWidget:
    type: app-extension
    platform: iOS
    sources:
      - path: WidgetExtension
        excludes:
          - "*.entitlements"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: $(BUNDLE_ID_PREFIX).lifewrapped.widget
        INFOPLIST_FILE: WidgetExtension/Info.plist
        CODE_SIGN_ENTITLEMENTS: WidgetExtension/WidgetExtension.entitlements
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SKIP_INSTALL: true
        IPHONEOS_DEPLOYMENT_TARGET: "18.0"
        SUPPORTS_MACCATALYST: true
        DERIVE_MACCATALYST_PRODUCT_BUNDLE_IDENTIFIER: true
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
      configs:
        Debug:
          xcconfig: Config/Debug.xcconfig
        Release:
          xcconfig: Config/Release.xcconfig
    dependencies:
      - package: SharedModels
      - package: Storage
      - package: InsightsRollup
      - sdk: WidgetKit.framework
      - sdk: SwiftUI.framework
